import type { Metadata } from "next";
import localFont from "next/font/local";
import { Oxygen, Playfair_Display } from "next/font/google"; // 1. Imports are correct
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

// 2. Setup the local font (Helvetica)
const helvetica = localFont({
  src: [
    {
      path: "../../public/fonts/Helvetica.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Helvetica-Bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-helvetica",
});

// 3. Setup the Google Font (Oxygen)
const oxygen = Oxygen({
  subsets: ["latin"],
  weight: "700", // Get the bold weight
  variable: "--font-oxygen-bold", // Assign a CSS variable
});

// 4. Setup Playfair Display for all variants
const playfair = Playfair_Display({
  subsets: ["latin"],
  // Request all available weights
  weight: ["400", "500", "600", "700", "800", "900"],
  // Request both normal and italic styles
  style: ["normal", "italic"],
  variable: "--font-playfair", // Assign a CSS variable
  display: "swap", // Good practice for font loading
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 5. Add the new font variable to the body tag */}
      <body
        className={`${helvetica.variable} ${oxygen.variable} ${playfair.variable} antialiased flex flex-col min-h-screen`}
      >
        <Navbar />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}