// src/app/api/chat/route.ts

import { NextRequest } from "next/server";

export async function POST(req: NextRequest) {
  const { messages } = await req.json();

  // This is a placeholder for your actual AI service call
  // For now, it simulates a streaming response
  const stream = new ReadableStream({
    async start(controller) {
      const encoder = new TextEncoder();
      const simulatedResponse = `This is a streamed response based on your query: "${
        messages[messages.length - 1].content
      }". In a real application, this would be generated by an AI model with access to the latest financial data.`;

      for (const char of simulatedResponse) {
        controller.enqueue(encoder.encode(char));
        await new Promise((resolve) => setTimeout(resolve, 20)); // Simulate delay
      }
      controller.close();
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
    },
  });
}